### ISSUE TITLE
Carrier mod

### ISSUE THREAD

**Issue by kittech0** [CammiePone/Cam-s-Wearable-Backpacks#11]
I can't wear any backpack when im trying to click on it shift+ right click it just grabs that backpack like from [carrier mod](https://www.curseforge.com/minecraft/mc-mods/carrier), is it possible to force wearing backpack and/or change keybinds?

**Comment by CammiePone** [comment]
The backpack goes on your back when you shift + right click it. If you have carrier installed, then yes, it wont work.

**Comment by kittech0** [comment]
> The backpack goes on your back when you shift + right click it. If you have carrier installed, then yes, it wont work.

so it makes backpacks kinda useless, is it possible to get like list of backpacks so i can blacklist them? mod:backpack

**Comment by CammiePone** [comment]
press F3 + H to see item IDs. And yea, just about any balanced backpack mod is useless with Carrier enabled. Carrier also fucks up Arcanus' Display Case because it has no checks to ensure a block doesn't do something special when you shift + right click it.

I do want to change up the backpack UI tho, so maybe in the future I'll make it so you just press a button to put it on your back.
